// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import kubgo "siigo.com/kubgo/src/domain/kubgo"
import mock "github.com/stretchr/testify/mock"

// IKubgoRepository is an autogenerated mock type for the IKubgoRepository type
type IKubgoRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *IKubgoRepository) Delete(_a0 *kubgo.Kubgo) chan error {
	ret := _m.Called(_a0)

	var r0 chan error
	if rf, ok := ret.Get(0).(func(*kubgo.Kubgo) chan error); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan error)
		}
	}

	return r0
}

// Save provides a mock function with given fields: _a0
func (_m *IKubgoRepository) Save(_a0 *kubgo.Kubgo) chan error {
	ret := _m.Called(_a0)

	var r0 chan error
	if rf, ok := ret.Get(0).(func(*kubgo.Kubgo) chan error); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan error)
		}
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *IKubgoRepository) Update(_a0 *kubgo.Kubgo) chan error {
	ret := _m.Called(_a0)

	var r0 chan error
	if rf, ok := ret.Get(0).(func(*kubgo.Kubgo) chan error); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan error)
		}
	}

	return r0
}
