trigger:
  - dev
  - sandbox
  - master
  - cicd

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: "Siigo/Siigo.Pipeline"

extends:
   
  template: go/golang-pipeline.yaml@Pipelines
  
  parameters:
    projectName: ms-kubgo
    environment: aks
    namespace: siigo-cross
    
    golangVersion: 1.18
    

