pipeline:
  name: test aws without bash
  identifier: test_aws_without_bash
  projectIdentifier: PoCGithub
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.pocbitbucket
        repoName: test
        build: <+input>
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: asdasd
                  identifier: asdasd
                  spec:
                    connectorRef: account.SiigoQAACR
                    image: "harness-tools:aws "
                    shell: Bash
                    command: |-
                      ls
                      aws --version

                      cat test.yaml
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.QACOLCluster
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
