// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// mockConstructorTestingTNewIKubgoService is an autogenerated mock type for the mockConstructorTestingTNewIKubgoService type
type mockConstructorTestingTNewIKubgoService struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: _a0
func (_m *mockConstructorTestingTNewIKubgoService) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// Errorf provides a mock function with given fields: format, args
func (_m *mockConstructorTestingTNewIKubgoService) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with given fields:
func (_m *mockConstructorTestingTNewIKubgoService) FailNow() {
	_m.Called()
}

// Logf provides a mock function with given fields: format, args
func (_m *mockConstructorTestingTNewIKubgoService) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
