// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import emptypb "google.golang.org/protobuf/types/known/emptypb"
import grpc "google.golang.org/grpc"
import kubgov1 "siigo.com/kubgo/src/api/proto/kubgo/v1"
import mock "github.com/stretchr/testify/mock"

// HealthServiceClient is an autogenerated mock type for the HealthServiceClient type
type HealthServiceClient struct {
	mock.Mock
}

// Health provides a mock function with given fields: ctx, in, opts
func (_m *HealthServiceClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*kubgov1.HealthResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *kubgov1.HealthResponse
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *kubgov1.HealthResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kubgov1.HealthResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
