// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import emptypb "google.golang.org/protobuf/types/known/emptypb"
import grpc "google.golang.org/grpc"
import kubgov1 "siigo.com/kubgo/src/api/proto/kubgo/v1"
import mock "github.com/stretchr/testify/mock"

// KubgoServiceClient is an autogenerated mock type for the KubgoServiceClient type
type KubgoServiceClient struct {
	mock.Mock
}

// AddKubgo provides a mock function with given fields: ctx, in, opts
func (_m *KubgoServiceClient) AddKubgo(ctx context.Context, in *kubgov1.AddKubgoRequest, opts ...grpc.CallOption) (*kubgov1.AddKubgoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *kubgov1.AddKubgoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *kubgov1.AddKubgoRequest, ...grpc.CallOption) *kubgov1.AddKubgoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kubgov1.AddKubgoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *kubgov1.AddKubgoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteKubgo provides a mock function with given fields: ctx, in, opts
func (_m *KubgoServiceClient) DeleteKubgo(ctx context.Context, in *kubgov1.DeleteKubgoRequest, opts ...grpc.CallOption) (*kubgov1.DeleteKubgoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *kubgov1.DeleteKubgoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *kubgov1.DeleteKubgoRequest, ...grpc.CallOption) *kubgov1.DeleteKubgoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kubgov1.DeleteKubgoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *kubgov1.DeleteKubgoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindKubgos provides a mock function with given fields: ctx, in, opts
func (_m *KubgoServiceClient) FindKubgos(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*kubgov1.FindKubgosResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *kubgov1.FindKubgosResponse
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) *kubgov1.FindKubgosResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kubgov1.FindKubgosResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKubgo provides a mock function with given fields: ctx, in, opts
func (_m *KubgoServiceClient) GetKubgo(ctx context.Context, in *kubgov1.GetKubgoRequest, opts ...grpc.CallOption) (*kubgov1.GetKubgoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *kubgov1.GetKubgoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *kubgov1.GetKubgoRequest, ...grpc.CallOption) *kubgov1.GetKubgoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kubgov1.GetKubgoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *kubgov1.GetKubgoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKubgo provides a mock function with given fields: ctx, in, opts
func (_m *KubgoServiceClient) UpdateKubgo(ctx context.Context, in *kubgov1.UpdateKubgoRequest, opts ...grpc.CallOption) (*kubgov1.UpdateKubgoResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *kubgov1.UpdateKubgoResponse
	if rf, ok := ret.Get(0).(func(context.Context, *kubgov1.UpdateKubgoRequest, ...grpc.CallOption) *kubgov1.UpdateKubgoResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kubgov1.UpdateKubgoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *kubgov1.UpdateKubgoRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
