// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeKubgoServiceServer is an autogenerated mock type for the UnsafeKubgoServiceServer type
type UnsafeKubgoServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedKubgoServiceServer provides a mock function with given fields:
func (_m *UnsafeKubgoServiceServer) mustEmbedUnimplementedKubgoServiceServer() {
	_m.Called()
}
